name: ebook
description: "An Islamic Ebook Library."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.4.0
  intl: ^0.18.0
  flutter_markdown:
  logger: ^2.0.1
  get: ^4.6.5
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  scroll_to_index:
  syncfusion_flutter_pdfviewer: ^24.2.7
  flutter_html:
  flutter_linkify: ^6.0.0
  http:
  skeletonizer:

  # Icons
  iconsax: ^0.0.8
  material_design_icons_flutter:

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash:
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/pdf/
  - assets/fonts/
  - assets/logos/
  - assets/images/banners/

  fonts:
    - family: broken
      fonts:
        - asset: assets/fonts/broken.ttf

    - family: jameelnoori
      fonts:
        - asset: assets/fonts/jameel_noori_nastaliq.ttf
